from __future__ import annotations

import hashlib
import unittest
from pathlib import Path

import numpy as np
import yaml

from the_fly_matrix.embodied_stability_metrics import (
    CAMPAIGN_PATH,
    StabilityMetricError,
    _load_campaign,
    measure_trajectory,
)
from the_fly_matrix.physical_trajectory import PhysicalTrajectory, SCHEMA_NAME, SCHEMA_VERSION


class EmbodiedStabilityMetricTests(unittest.TestCase):
    def _trajectory(self, *, include_forces: bool = True) -> PhysicalTrajectory:
        timestamps = np.asarray([0.1, 0.2, 0.3])
        qpos = np.zeros((3, 9), dtype=float)
        qpos[:, 3] = 1.0
        qpos[:, 0] = [0.0, 0.3, 0.4]
        qpos[:, 2] = [1.0, 0.9, 0.8]
        qvel = np.zeros((3, 8), dtype=float)
        qvel[:, 0] = [0.0, 1.0, 2.0]
        commands = np.asarray([[0.0, 0.0], [0.1, -0.1], [0.2, -0.1]])
        neural = np.asarray(
            [
                [0.0, 0.1, -0.2, 0.3, 0.5, 0.0],
                [0.0, 0.2, -0.4, 0.5, 0.6, 0.1],
                [0.0, 0.3, -0.6, 0.7, 0.7, 0.2],
            ]
        )
        joint_state = np.asarray(
            [[0.0, 0.0, 0.0, 0.0], [0.1, 0.2, 1.0, 2.0], [0.2, 0.3, 2.0, 3.0]]
        )
        contacts = np.zeros((3, 6, 16), dtype=float)
        contacts[0, :2, 0] = 1.0
        contacts[1, :3, 0] = 1.0
        contacts[2, 1:3, 0] = 1.0
        sensory = {
            "joint_state": joint_state,
            "ground_contacts": contacts.reshape(3, -1),
        }
        if include_forces:
            sensory["actuator_forces"] = np.ones((3, 2), dtype=float)
        return PhysicalTrajectory(
            timestamps_s=timestamps,
            qpos=qpos,
            qvel=qvel,
            actuator_commands=commands,
            neural_summary=neural,
            sensory_observations=sensory,
            metadata={
                "schema_name": SCHEMA_NAME,
                "schema_version": SCHEMA_VERSION,
                "claim_label": "TEST ONLY",
                "model": {
                    "nq": 9,
                    "nv": 8,
                    "nu": 2,
                    "actuator_names": ["a", "b"],
                },
            },
        )

    def test_descriptive_metrics_do_not_invent_unavailable_quantities(self) -> None:
        metrics = measure_trajectory(self._trajectory())
        self.assertAlmostEqual(
            metrics["root_state"]["translation_from_initial"]["peak_l2"],
            np.sqrt(0.4**2 + 0.2**2),
        )
        self.assertEqual(metrics["contacts"]["transition_count_total"], 2)
        self.assertEqual(metrics["contacts"]["contacting_legs"]["maximum"], 3)
        self.assertEqual(metrics["central_summary"]["maximum_absolute_state_summary"], 0.7)
        self.assertIsNone(metrics["joints"]["limit_violation_count"])
        self.assertIn("center_of_mass_displacement", metrics["unavailable_metrics"])
        self.assertIn("command_slew_not_body_jerk", metrics["actuation"])

    def test_required_sensor_absence_is_an_error_not_a_zero_default(self) -> None:
        with self.assertRaisesRegex(StabilityMetricError, "actuator_forces"):
            measure_trajectory(self._trajectory(include_forces=False))

    def test_campaign_is_value_free_and_cannot_accept_stability(self) -> None:
        campaign = _load_campaign(CAMPAIGN_PATH)
        self.assertEqual(campaign["optimization_exposure"], "diagnostic_only")
        self.assertEqual(campaign["behavior_targets"], [])
        self.assertEqual(campaign["budgets"]["optimized_parameters"], 0)
        self.assertEqual(campaign["acceptance"]["stability_thresholds"], "unresolved")
        self.assertFalse(campaign["acceptance"]["stability_acceptance_possible"])

    def test_campaign_yaml_has_no_hidden_behavior_target(self) -> None:
        campaign = yaml.safe_load(CAMPAIGN_PATH.read_text(encoding="utf-8"))
        self.assertNotIn("groom", str(campaign).lower())
        self.assertNotIn("walking", str(campaign).lower())

    def test_versioned_result_cannot_claim_stability(self) -> None:
        result_path = Path("calibration/runner/embodied-stability-metric-contract-v0.yaml")
        if not result_path.is_file():
            self.skipTest("compact result is generated by the diagnostic runner")
        result = yaml.safe_load(result_path.read_text(encoding="utf-8"))
        self.assertEqual(result["accounting"]["optimized_parameters"], 0)
        self.assertEqual(result["accounting"]["behavior_targets_exposed"], 0)
        self.assertFalse(result["interpretation"]["stability_accepted"])
        self.assertFalse(result["interpretation"]["motion_is_biological_behavior"])
        self.assertEqual(len(result["semantic_result_sha256"]), 64)

    def test_evaluation_hash_locks_campaign_and_implementation(self) -> None:
        evaluation = yaml.safe_load(
            Path("calibration/evaluations/embodied-stability-metric-contract-v0.yaml")
            .read_text(encoding="utf-8")
        )
        for key in ("campaign", "implementation"):
            locked = evaluation["reproducibility"][key]
            path = Path(locked["path"])
            actual = hashlib.sha256(path.read_bytes()).hexdigest()
            self.assertEqual(actual, locked["sha256"])


if __name__ == "__main__":
    unittest.main()
